sudo: required
dist: trusty
language: cpp
cache: ccache

# set the CMAKE_PREFIX_PATH enviroment variable to get software installed by the superbuild
matrix:
  include:
    - os: linux
      compiler: clang
      env: TRAVIS_CMAKE_GENERATOR="Unix Makefiles", TRAVIS_BUILD_TYPE="Debug"
    - os: linux
      compiler: clang
      env: TRAVIS_CMAKE_GENERATOR="Unix Makefiles", TRAVIS_BUILD_TYPE="Release"
    - os: linux
      compiler: gcc
      env: TRAVIS_CMAKE_GENERATOR="Unix Makefiles", TRAVIS_BUILD_TYPE="Debug"
    - os: linux
      compiler: gcc
      env: TRAVIS_CMAKE_GENERATOR="Unix Makefiles", TRAVIS_BUILD_TYPE="Release"
    - os: osx
      compiler: gcc
      env: TRAVIS_CMAKE_GENERATOR="Unix Makefiles", TRAVIS_BUILD_TYPE="Debug"
    - os: osx
      compiler: clang
      env: TRAVIS_CMAKE_GENERATOR="Xcode", TRAVIS_BUILD_TYPE="Release"


before_script:
  - cd ..  
  # use superbuild for getting codyco-modules dependencies
  - git clone https://github.com/robotology/codyco-superbuild
  - cd codyco-superbuild
  - pwd
  # install dependencies using the codyco-superbuild script
  - chmod +x ./.ci/travis-deps.sh
  - sh .ci/travis-deps.sh
  - mkdir build
  - cd build
  - export CMAKE_PREFIX_PATH=`pwd`/install
  # using the YCM_EP_MAINTAINER_MODE variable to enable the subproject-dependees target
  - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCODYCO_TRAVIS_CI:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DYCM_EP_MAINTAINER_MODE:BOOL=ON -DNON_INTERACTIVE_BUILD:BOOL=TRUE ..
  - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target codyco-modules-dependees
  - cd ../..
  # go back to codyco-modules
  - cd codyco-modules

script:
  - mkdir build
  - cd build
  - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCODYCO_TRAVIS_CI:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DNON_INTERACTIVE_BUILD:BOOL=TRUE ..
  - cmake --build . --config ${TRAVIS_BUILD_TYPE}

notifications:
  email:
    - pegua1@gmail.com
